### ISSUE TITLE
Duplicate SPASE id

### ISSUE THREAD

**Issue by BaptisteCecconi** [hpde/SMWG#16] opened 2022-02-02 15:54 UTC
There are 2 SPASE records with the same ID:
- [Cesar.Garcia.Marirrodriga.xml](https://github.com/hpde/SMWG/blob/master/Person/Cesar.Garcia.Marirrodriga.xml)
- [Cesar.Garcia.xml](https://github.com/hpde/SMWG/blob/master/Person/Cesar.Garcia.xml)

The SPASE id is `spase://SMWG/Person/Cesar.Garcia.Marirrodriga` in both records.

**Comment by toddking** [comment] 2022-02-03 16:33
Removed Cesar.Garcia.xml which was a duplicate of Cesar.Garcia.Marirrodriga.xml with a different file name.

**Closed as completed by toddking** 2022-02-03 16:33 UTC
